# Generated by Django 6.0.7 on 2026-08-07 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_companyregistration_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('Phone', models.CharField(max_length=15)),
                ('Alternate_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('Role', models.CharField(choices=[('Manager', 'Manager'), ('Cashier', 'Cashier'), ('Worker', 'Worker')], max_length=30)),
                ('joining_date', models.DateField()),
                ('monthaly_salary', models.CharField(max_length=10)),
                ('payment', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Due', 'Due')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.companyregistration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
