# Generated by Django 6.0.7 on 2026-08-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='monthaly_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
