# Generated by Django 5.2.17 on 2026-10-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_user_registration_monthaly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='Role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Cashier', 'Cashier'), ('Stock Manager', 'Stock Manager'), ('Worker', 'Worker')], max_length=30),
        ),
    ]
