# Generated by Django 5.2.17 on 2026-10-08 09:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_companyregistration_owner'),
        ('inventory', '0006_product_prevent_negative_stock'),
        ('sales', '0002_checkoutidempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSScannerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pairing_code', models.CharField(db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONNECTED', 'Disconnected'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_ping', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_sessions', to='accounts.companyregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanner_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POSScannerScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='sales.posscannersession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged'), ('WRONG_PRODUCT', 'Wrong Product'), ('EXPIRED', 'Expired'), ('QUALITY_ISSUE', 'Quality Issue'), ('CUSTOMER_CHANGED_MIND', 'Customer Changed Mind'), ('OTHER', 'Other')], default='CUSTOMER_CHANGED_MIND', max_length=30)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('refund_payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR Code'), ('CARD', 'Debit / Credit Card'), ('CREDIT', 'Store Credit')], default='CASH', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='accounts.companyregistration')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='sales.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='sales.invoice')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='sales.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('refund_unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('refund_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('restock', models.BooleanField(default=True, help_text='If true, item is returned to sellable stock. If false (e.g. damaged/expired), stock is not restored.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returned_items', to='inventory.product')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_records', to='sales.saleitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.returnrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['company', 'created_at'], name='sales_retur_company_0a42e5_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['company', 'status'], name='sales_retur_company_52be2c_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['company', 'return_number'], name='sales_retur_company_e68f1d_idx'),
        ),
    ]
