# Generated by Django 5.2.17 on 2026-10-08 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_companyregistration_owner'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramoutboundmessage',
            name='media_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='telegramoutboundmessage',
            name='media_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='telegramoutboundmessage',
            name='media_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('DOCUMENT', 'Document'), ('PHOTO', 'Photo')], default='TEXT', max_length=20),
        ),
        migrations.CreateModel(
            name='RemoteSyncedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=30)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('entity_identifier', models.CharField(max_length=100)),
                ('payload_summary', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_synced_records', to='accounts.companyregistration')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='RemoteSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('SYNCING', 'Syncing'), ('ERROR', 'Error')], default='ONLINE', max_length=20)),
                ('last_sync_success', models.DateTimeField(blank=True, null=True)),
                ('last_sync_attempt', models.DateTimeField(blank=True, null=True)),
                ('pending_count', models.IntegerField(default=0)),
                ('total_synced_count', models.IntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_status', to='accounts.companyregistration')),
            ],
            options={
                'verbose_name': 'Remote Sync Status',
                'verbose_name_plural': 'Remote Sync Statuses',
            },
        ),
        migrations.CreateModel(
            name='SyncQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=30)),
                ('entity_id', models.CharField(max_length=100)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to='accounts.companyregistration')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='dashboard_s_company_8b6ac0_idx'), models.Index(fields=['idempotency_key'], name='dashboard_s_idempot_63ff13_idx')],
            },
        ),
    ]
