# Generated by Django 5.2.17 on 2026-10-05 13:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_companyregistration_owner'),
        ('inventory', '0005_product_unique_company_barcode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('current_stock__gte', Decimal('0.00'))), name='prevent_negative_stock'),
        ),
    ]
